######### 锚点 start #######
# 策略组相关
# pr=节点选择 prm=Match pra=Apple prme=MicroSoft,Emby
pr: &pr {type: select, proxies: [HK, SG, JP, US, TW, DIRECT], include-all-providers: true, exclude-filter: "Expire|Traffic"}
prm: &prm {type: select, proxies: [Proxies, DIRECT]} 
pra: &pra {type: select, proxies: [DIRECT, Proxies]} 
prme: &prme {type: select, proxies: [DIRECT], include-all-providers: true, filter: "(?i)实验性|家宽"}
#这里是订阅更新和延迟测试相关的
p: &p {type: http, interval: 21600, health-check: {enable: true, url: 'https://www.gstatic.com/generate_204', interval: 600}}
######### 锚点 end #######

proxy-providers:
  Flower_Trojan:
    <<: *p
    url: "订阅链接"
    override:
      ip-version: ipv4

#  provider2:
#    <<: *p
#    url: ""
dns:
  nameserver:
   - 61.128.114.134
   - 61.128.114.167
   - "[240e:51:c800:4::4]:53"
   - "[240e:51:c800:8::8]:53"
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query

  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.qq.com"
  - "+.tencent.com"
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.cdn.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - na.b.g-tun.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - local.adguard.org
  - "+.sandai.net"
  - "+.n0808.com"
  - "+.uu.163.com"
  - ps.res.netease.com
  - "+.ipw.cn"
  - "+.push.apple.com"
  - "+.courier-push-apple.com.akadns.net"

proxy-groups:
  - {name: Proxies, <<: *pr}
  - {name: Match, <<: *prm}
  - {name: MicroSoft, <<: *prme}
  - {name: Games, <<: *pr}
  - {name: Apple, <<: *pra}
  - {name: Emby, <<: *prme}

#分隔,下面是地区分组
  - {name: HK, type: url-test , include-all-providers: true, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: SG, type: url-test , include-all-providers: true, filter: "(?i)新|狮城|SG|Singapore"}
  - {name: TW, type: url-test , include-all-providers: true, filter: "(?i)台|新北|彰化|TW|Taiwan"}
  - {name: JP, type: url-test , include-all-providers: true, filter: "(?i)日|东京|大阪|埼玉|JP|Japan"}
  - {name: US, type: url-test , include-all-providers: true, filter: "(?i)美|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|USA|America"}

rules:
  - RULE-SET,Reject,REJECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,CHN,DIRECT
  - RULE-SET,CHN-IP,DIRECT,no-resolve
  - RULE-SET,Apple,Apple
  - RULE-SET,Proxy,Proxies
  - RULE-SET,Telegram,Proxies
  - RULE-SET,Emby,Emby
  - RULE-SET,Microsoft,MicroSoft
  - RULE-SET,Games,Games
  - RULE-SET,OpenAI,US
  - RULE-SET,BanAD,REJECT
  - RULE-SET,BanProgramAD,REJECT
  - IP-CIDR6,::/1,REJECT,no-resolve
  - MATCH,Match

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: text}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: text}
  classical: &classical {type: http, interval: 86400, behavior: classical, format: text}
rule-providers:
  Reject:
    <<: *classical
    url: "https://raw.githubusercontent.com/cutbuzz/rules/main/clash/reject.list"
  BanAD:
    <<: *classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
  BanProgramAD:
    <<: *classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
  Direct:
    <<: *classical
    url: "https://raw.githubusercontent.com/cutbuzz/rules/main/clash/direct.list"
  CHN:
    <<: *classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMaxNoIP/ChinaMaxNoIP.list"
  CHN-IP:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.list"
  Apple:
    <<: *classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
  Proxy:
    <<: *classical
    url: "https://raw.githubusercontent.com/cutbuzz/rules/main/clash/proxy.list"
  Telegram:
    <<: *classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"
  Emby:
    <<: *classical
    url: "https://raw.githubusercontent.com/cutbuzz/rules/main/clash/amby.list"
  Microsoft:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/microsoft.list"
  Games:
    <<: *classical
    url: "https://raw.githubusercontent.com/cutbuzz/rules/main/clash/games.list"
  OpenAI:
    <<: *classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list"